version: 2.1

jobs:
  sonar-scanner:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout
      - run:
          name: Install Sonar Scanner
          command: |
            curl -sL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip -o sonar-scanner.zip
            unzip sonar-scanner.zip -d $HOME
            export PATH=$HOME/sonar-scanner-4.6.2.2472-linux/bin:$PATH
      - run:
          name: Run SonarQube Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=YOUR_PROJECT_KEY \
              -Dsonar.organization=YOUR_ORG_NAME \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  sonar-scan-workflow:
    jobs:
      - sonar-scanner
